[workspace]

resolver = "2"

members = [
    "freemework_abstractions",
    "freemework_common",
    "freemework_jsonrpc",
]

[workspace.package]
version = "0.1.0"
authors = ["Freemework Developers"]
edition = "2024"
description = "TBD"
documentation = "https://docs.freemework.org/"
license-file = "LICENSE"
publish = ["freemework"]

[workspace.dependencies]
freemework_abstractions = { version = "0.1.0", path = "freemework_abstractions", registry = "freemework" }
freemework_common = { version = "0.1.0", path = "freemework_common", registry = "freemework" }
freemework_jsonrpc = { version = "0.1.0", path = "freemework_jsonrpc", registry = "freemework" }
