kind: template
load: edgebus-ops.star
data:
  stages:
    - kind: build.cargo.package
      ref_branch: "src-rust#dev"
      name: freemework_abstractions
      configuration: snapshot
      workspace-package: freemework_abstractions
      registry:
        - name: "freemework"
          secret-ref: "CARGO_REGISTRY_TOKEN"
    - kind: build.cargo.package
      ref_branch: "src-rust#dev"
      name: freemework_common
      configuration: snapshot
      workspace-package: freemework_common
      workspace-package-deps:
        - freemework_abstractions
      registry:
        - name: "freemework"
          secret-ref: "CARGO_REGISTRY_TOKEN"
    - kind: build.cargo.package
      ref_branch: "src-rust#dev"
      name: freemework_jsonrpc
      configuration: snapshot
      workspace-package: freemework_jsonrpc
      workspace-package-deps:
        - freemework_abstractions
      registry:
        - name: "freemework"
          secret-ref: "CARGO_REGISTRY_TOKEN"
